[mypy]
python_version = 3.12
strict = True
plugins = pydantic.mypy
warn_unused_ignores = False

[mypy-boto3]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-boto3.*]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-botocore]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-botocore.*]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-defusedxml]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-defusedxml.*]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-olefile]
ignore_missing_imports = True
disable_error_code = import-untyped
