/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/db": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Database Health */
    get: operations["database_health_health_db_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/access": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Portal Access */
    get: operations["portal_access_api_v1_auth_access_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Leads */
    get: operations["get_leads_api_v1_leads_get"];
    put?: never;
    /** Submit Lead */
    post: operations["submit_lead_api_v1_leads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{lead_id}/marketing-consent/withdrawal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Withdraw Lead Marketing Consent */
    post: operations["withdraw_lead_marketing_consent_api_v1_leads__lead_id__marketing_consent_withdrawal_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations/mortgage-application": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mortgage Application Redirect */
    get: operations["mortgage_application_redirect_api_v1_integrations_mortgage_application_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/candidates/{candidate_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition Candidate */
    post: operations["transition_candidate_api_v1_candidates__candidate_id__status_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agents/{profile_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition Agent Profile */
    post: operations["transition_agent_profile_api_v1_agents__profile_id__status_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/{document_id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download Candidate Document */
    get: operations["download_candidate_document_api_v1_documents__document_id__download_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccessResponse */
    AccessResponse: {
      /** Allowed */
      allowed: boolean;
      /** Area */
      area: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Roles */
      roles: string[];
    };
    /**
     * AgentProfileStatus
     * @enum {string}
     */
    AgentProfileStatus:
      | "draft"
      | "pending_approval"
      | "published"
      | "suspended"
      | "archived";
    /** AgentStatusResponse */
    AgentStatusResponse: {
      status: components["schemas"]["AgentProfileStatus"];
    };
    /** AgentTransitionRequest */
    AgentTransitionRequest: {
      status: components["schemas"]["AgentProfileStatus"];
      /** Reason */
      reason?: string | null;
    };
    /**
     * CandidateStatus
     * @enum {string}
     */
    CandidateStatus:
      | "prospect"
      | "application_started"
      | "application_submitted"
      | "under_review"
      | "more_information_required"
      | "interview"
      | "conditionally_selected"
      | "declined"
      | "withdrawn"
      | "onboarding_in_progress"
      | "pending_fsra_authorization"
      | "pending_system_provisioning"
      | "active"
      | "suspended"
      | "offboarding"
      | "offboarded";
    /** CandidateStatusResponse */
    CandidateStatusResponse: {
      status: components["schemas"]["CandidateStatus"];
    };
    /** CandidateTransitionRequest */
    CandidateTransitionRequest: {
      status: components["schemas"]["CandidateStatus"];
      /** Reason */
      reason?: string | null;
    };
    /** ConsentState */
    ConsentState: {
      /**
       * State
       * @enum {string}
       */
      state: "granted" | "withdrawn";
      /**
       * Granted At
       * Format: date-time
       */
      granted_at: string;
      /** Withdrawn At */
      withdrawn_at: string | null;
    };
    /** DatabaseHealthResponse */
    DatabaseHealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unavailable";
      /**
       * Database
       * @enum {string}
       */
      database: "reachable" | "unreachable";
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Service */
      service: string;
    };
    /** LeadInquiryCreate */
    LeadInquiryCreate: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Telephone */
      telephone: string;
      /**
       * Mortgage Objective
       * @enum {string}
       */
      mortgage_objective:
        | "purchase"
        | "refinance"
        | "renewal"
        | "investment"
        | "other";
      /**
       * Preferred Contact Method
       * @enum {string}
       */
      preferred_contact_method: "email" | "telephone";
      /** Preferred Agent Slug */
      preferred_agent_slug?: string | null;
      /** Message */
      message?: string | null;
      /** Service Contact Acknowledged */
      service_contact_acknowledged: boolean;
      /**
       * Marketing Consent
       * @default false
       */
      marketing_consent: boolean;
      /**
       * Website
       * @default
       */
      website: string;
    };
    /** LeadInquiryCreated */
    LeadInquiryCreated: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Marketing Consent Recorded */
      marketing_consent_recorded: boolean;
    };
    /** LeadListItem */
    LeadListItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Telephone */
      telephone: string;
      /**
       * Mortgage Objective
       * @enum {string}
       */
      mortgage_objective:
        | "purchase"
        | "refinance"
        | "renewal"
        | "investment"
        | "other";
      /**
       * Preferred Contact Method
       * @enum {string}
       */
      preferred_contact_method: "email" | "telephone";
      /** Preferred Agent Slug */
      preferred_agent_slug: string | null;
      /** Message */
      message: string | null;
      /** Source */
      source: string;
      /**
       * Status
       * @enum {string}
       */
      status: "new" | "assigned" | "contacted" | "closed";
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      service_consent: components["schemas"]["ConsentState"];
      marketing_consent: components["schemas"]["ConsentState"] | null;
    };
    /** LeadListResponse */
    LeadListResponse: {
      /** Items */
      items: components["schemas"]["LeadListItem"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  database_health_health_db_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatabaseHealthResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatabaseHealthResponse"];
        };
      };
    };
  };
  portal_access_api_v1_auth_access_get: {
    parameters: {
      query: {
        area: "candidate" | "admin";
      };
      header?: {
        "x-dev-auth-sub"?: string | null;
        "x-dev-auth-aal"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_leads_api_v1_leads_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        status?: ("new" | "assigned" | "contacted" | "closed") | null;
      };
      header?: {
        "x-dev-auth-sub"?: string | null;
        "x-dev-auth-aal"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadListResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Administrator access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_lead_api_v1_leads_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadInquiryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadInquiryCreated"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Contact submission rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  withdraw_lead_marketing_consent_api_v1_leads__lead_id__marketing_consent_withdrawal_post: {
    parameters: {
      query?: never;
      header?: {
        "x-dev-auth-sub"?: string | null;
        "x-dev-auth-aal"?: string;
      };
      path: {
        lead_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentState"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Administrator access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Lead or marketing consent unavailable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mortgage_application_redirect_api_v1_integrations_mortgage_application_get: {
    parameters: {
      query?: {
        agent?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Configured application destination unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  transition_candidate_api_v1_candidates__candidate_id__status_post: {
    parameters: {
      query?: never;
      header?: {
        "x-dev-auth-sub"?: string | null;
        "x-dev-auth-aal"?: string;
      };
      path: {
        candidate_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CandidateTransitionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transition_agent_profile_api_v1_agents__profile_id__status_post: {
    parameters: {
      query?: never;
      header?: {
        "x-dev-auth-sub"?: string | null;
        "x-dev-auth-aal"?: string;
      };
      path: {
        profile_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentTransitionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_candidate_document_api_v1_documents__document_id__download_get: {
    parameters: {
      query?: never;
      header?: {
        "x-dev-auth-sub"?: string | null;
        "x-dev-auth-aal"?: string;
      };
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
