FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY apps/web/package.json apps/web/package.json
COPY packages/ui/package.json packages/ui/package.json
COPY packages/contracts/package.json packages/contracts/package.json
RUN npm ci

FROM node:22-alpine AS build
WORKDIR /app
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BROKERAGE_DISPLAY_NAME
ARG NEXT_PUBLIC_BROKERAGE_LEGAL_NAME
ARG NEXT_PUBLIC_BROKERAGE_REGULATORY_TEXT
ARG NEXT_PUBLIC_PUBLIC_ADDRESS
ARG NEXT_PUBLIC_PUBLIC_EMAIL
ARG NEXT_PUBLIC_PUBLIC_PHONE
ARG NEXT_PUBLIC_PUBLIC_PHONE_E164
ARG NEXT_PUBLIC_MORTGAGE_APPLICATION_URL
ARG NEXT_PUBLIC_BOOKING_URL
ARG NEXT_PUBLIC_PRINCIPAL_BROKER
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_BROKERAGE_DISPLAY_NAME=$NEXT_PUBLIC_BROKERAGE_DISPLAY_NAME \
    NEXT_PUBLIC_BROKERAGE_LEGAL_NAME=$NEXT_PUBLIC_BROKERAGE_LEGAL_NAME \
    NEXT_PUBLIC_BROKERAGE_REGULATORY_TEXT=$NEXT_PUBLIC_BROKERAGE_REGULATORY_TEXT \
    NEXT_PUBLIC_PUBLIC_ADDRESS=$NEXT_PUBLIC_PUBLIC_ADDRESS \
    NEXT_PUBLIC_PUBLIC_EMAIL=$NEXT_PUBLIC_PUBLIC_EMAIL \
    NEXT_PUBLIC_PUBLIC_PHONE=$NEXT_PUBLIC_PUBLIC_PHONE \
    NEXT_PUBLIC_PUBLIC_PHONE_E164=$NEXT_PUBLIC_PUBLIC_PHONE_E164 \
    NEXT_PUBLIC_MORTGAGE_APPLICATION_URL=$NEXT_PUBLIC_MORTGAGE_APPLICATION_URL \
    NEXT_PUBLIC_BOOKING_URL=$NEXT_PUBLIC_BOOKING_URL \
    NEXT_PUBLIC_PRINCIPAL_BROKER=$NEXT_PUBLIC_PRINCIPAL_BROKER
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build --workspace @keeper/web

FROM node:22-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app
COPY --chown=node:node --from=build /app/apps/web/.next/standalone ./
COPY --chown=node:node --from=build /app/apps/web/.next/static ./apps/web/.next/static
COPY --chown=node:node --from=build /app/apps/web/public ./apps/web/public
EXPOSE 3000
USER node
CMD ["node", "apps/web/server.js"]
